### ISSUE TITLE
Crash with Disc Drive (1.1 for BTA)

### ISSUE THREAD

**Issue by MrMirajIzHere** [MartinSVK12/retrostorage#24]
if you pop disk in disc drive, then unpower it and break it game will crash (only in survival)

[22:19:52] [Minecraft main thread] java.lang.NullPointerException: Cannot invoke "net.minecraft.src.ItemStack.copy()" because the return value of "sunsetsatellite.retrostorage.tiles.TileEntityDiscDrive.getStackInSlot(int)" is null
[22:19:52] [Minecraft main thread] 	at sunsetsatellite.retrostorage.blocks.BlockDiscDrive.onBlockRemoval(BlockDiscDrive.java:46)
[22:19:52] [Minecraft main thread] 	at net.minecraft.src.Chunk.setBlockID(Chunk.java:317)
[22:19:52] [Minecraft main thread] 	at net.minecraft.src.World.setBlock(World.java:598)
[22:19:52] [Minecraft main thread] 	at net.minecraft.src.World.setBlockWithNotify(World.java:727)
[22:19:52] [Minecraft main thread] 	at net.minecraft.src.PlayerController.destroyBlock(PlayerController.java:128)
[22:19:52] [Minecraft main thread] 	at net.minecraft.src.PlayerControllerSP.destroyBlock(PlayerControllerSP.java:14)
[22:19:52] [Minecraft main thread] 	at net.minecraft.src.PlayerController.mine(PlayerController.java:99)
[22:19:52] [Minecraft main thread] 	at net.minecraft.client.Minecraft.mineBlocks(Minecraft.java:909)
[22:19:52] [Minecraft main thread] 	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1455)
[22:19:52] [Minecraft main thread] 	at net.minecraft.client.Minecraft.run(Minecraft.java:3369)
[22:19:52] [Minecraft main thread] 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by MartinSVK12** [comment]
Fixed in 1.1.1.
